spring:
  application:
    name: web-gagebu

  profiles:
    active: default

  threads:
    virtual:
      enabled: true

  mvc:
    log-resolved-exception: false

  datasource:
    url: jdbc:postgresql://localhost:42300/web_gagebu
    username: admin
    password: admin123123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <GOOGLE_CLIENT_ID>
            client-secret: <GOOGLE_CLIENT_SECRET>
            redirect-uri: "{baseUrl}/api/v1/oauth2/code/google"
            scope:
              - openid
              - profile
              - email

server:
  port: 8080
  forward-headers-strategy: framework

logging:
  config: classpath:log4j2-spring.xml

app:
  encryption:
    key: <ENCRYPTION_KEY>

  auth:
    jwt:
      private-key: |
        <PKCS8_PRIVATE_KEY>
      public-key: |
        <PUBLIC_KEY>
      expiration: 7d
      renewal: 1d

  invitation:
    cleanup:
      rate: 5m
