spring:
  main:
    banner-mode: off

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

app:
  cors:
    allowed-origins:
      - "https://yourdomain.com"
      - "https://www.yourdomain.com"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "PATCH"
      - "OPTIONS"
    allowed-headers:
      - "Authorization"
      - "Content-Type"
      - "Accept"
      - "Origin"
      - "X-Requested-With"
    allow-credentials: true
    path-pattern: "/**"
